<div id="rcmPortalOptions">
    <?= $this->instanceConfig['html'] ?>

        <div class="tipFlyOut hidden">Right Click To Edit</div>
        <div class="row addNew">
            <div class="col-xs-12">
                <a>
                    <div class="addNewItem hidden">
                    <span class="glyphicon glyphicon-plus">
                    </span>
                    </div>
                </a>
            </div>
        </div>
    </div>