
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-4 col-xs-12">
                <div class="portalMenuItem">
                    <div class="removeItem">
                        <a>
                            <span class="glyphicon glyphicon-remove"></span>
                        </a>
                    </div>
                    <div class="editItem">
                        <a>
                            <span class="glyphicon glyphicon-pencil"></span>
                        </a>
                    </div>
                    <div class="menuItem">
                        <div>
                            <span>
                                <a href="">Link Title</a>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4 col-xs-12">
                <a>
                    <div class="addNewItem">
                    <span class="glyphicon glyphicon-plus">
                    </span>
                    </div>
                </a>
            </div>
        </div>
    </div>